if: NOT (commit_message =~ /^\[docs\]/)

language: node_js
node_js: "stable"

addons:
  chrome:  stable
  firefox: latest
  apt:
    packages:
      - dbus

before_install:
  - export $(dbus-launch)

notifications:
  email: false
